In [72]:
import pandas as pd
!jupyter kernelspec list 
!which -a python

# import sys
# !{sys.executable} -m pip install yfinance requests_cache requests_ratelimiter pyrate_limiter
import yfinance as yf
import requests

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Available kernels:
  miniconda3    /Users/abdurrahmanabulhossain/Library/Jupyter/kernels/miniconda3
  python3       /Library/Frameworks/Python.framework/Versions/3.11/share/jupyter/kernels/python3
/Users/abdurrahmanabulhossain/Documents/My-Projects/Stock Screen alpha vantage/.venv/bin/python
/Users/abdurrahmanabulhossain/miniconda3/bin/python

In [73]:
df= pd.read_csv('datas/tsx-60-index-11-15-2023.csv')
df

,Symbol,Name,Last,Change,%Chg,Open,High,Low,Volume,Time
0,ABX.TO,Barrick Gold Corp,21.36,-0.15,-0.70%,21.43,21.54,21.23,2636841.0,2023-11-15
1,AEM.TO,Agnico Eagle Mines Ltd,65.41,-0.62,-0.94%,65.78,66.22,65.11,834991.0,2023-11-15
2,AQN.TO,Algonquin Power and Utilities Corp,7.95,0.00,0.00%,7.94,7.99,7.84,3138478.0,2023-11-15
3,ATD.TO,Alimentation Couche-Tard Inc.,77.38,-1.16,-1.48%,79.00,79.12,77.19,1478569.0,2023-11-15
4,BAM.TO,Brookfield Asset Management Ltd,45.94,1.17,+2.61%,44.87,46.09,44.87,1273480.0,2023-11-15
...,...,...,...,...,...,...,...,...,...,...
56,WCN.TO,Waste Connections Inc,183.37,-1.45,-0.78%,184.94,185.74,183.22,198841.0,2023-11-15
57,WN.TO,Weston George,162.18,-5.49,-3.27%,168.13,168.19,162.11,176338.0,2023-11-15
58,WPM.TO,Wheaton Precious Metals Corp,60.99,-0.38,-0.62%,61.37,61.41,60.41,535666.0,2023-11-15
59,WSP.TO,WSP Global Inc,193.09,0.14,+0.07%,192.95,194.77,192.81,145050.0,2023-11-15
60,Downloaded from Barchart.com as of 11-15-2023 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
# df['Symbol'] = df['Symbol'].str[:-3] + ':TSX'
df = df.iloc[:-1][['Symbol']]
df

       Symbol
0      ABX.TO
1      AEM.TO
2      AQN.TO
3      ATD.TO
4      BAM.TO
5      BCE.TO
6   BIP-UN.TO
7      BMO.TO
8       BN.TO
9      BNS.TO
10     CAE.TO
11  CAR-UN.TO
12   CCL-B.TO
13     CCO.TO
14      CM.TO
15     CNQ.TO
16     CNR.TO
17      CP.TO
18     CSU.TO
19   CTC-A.TO
20     CVE.TO
21     DOL.TO
22     EMA.TO
23     ENB.TO
24      FM.TO
25     FNV.TO
26     FSV.TO
27     FTS.TO
28   GIB-A.TO
29     GIL.TO
30       H.TO
31     IFC.TO
32     IMO.TO
33       K.TO
34       L.TO
35     MFC.TO
36      MG.TO
37     MRU.TO
38      NA.TO
39     NTR.TO
40    OTEX.TO
41     POW.TO
42     PPL.TO
43     QSR.TO
44   RCI-B.TO
45      RY.TO
46     SAP.TO
47    SHOP.TO
48     SLF.TO
49      SU.TO
50       T.TO
51      TD.TO
52  TECK-B.TO
53     TOU.TO
54     TRI.TO
55     TRP.TO
56     WCN.TO
57      WN.TO
58     WPM.TO
59     WSP.TO

In [75]:


# # replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
# url = 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=CAR-UN.TRT&apikey=9AP22VC3JPOUAYSK'
# r = requests.get(url)
# data = r.json()

# print(data)

In [76]:
# df['Date'] = [None] * len(df)
# df['Net_Income'] = [None] * len(df)
# df['Total_Assets'] = [None] * len(df)
# df['Equity'] = [None] * len(df)
# df['P/E_Ratio'] = [None] * len(df)
# df['Price'] = [None] * len(df)
df['ROA_TTM'] = [None] * len(df)
df['ROE_TTM'] = [None] * len(df)
df

       Symbol ROA_TTM ROE_TTM
0      ABX.TO    None    None
1      AEM.TO    None    None
2      AQN.TO    None    None
3      ATD.TO    None    None
4      BAM.TO    None    None
5      BCE.TO    None    None
6   BIP-UN.TO    None    None
7      BMO.TO    None    None
8       BN.TO    None    None
9      BNS.TO    None    None
10     CAE.TO    None    None
11  CAR-UN.TO    None    None
12   CCL-B.TO    None    None
13     CCO.TO    None    None
14      CM.TO    None    None
15     CNQ.TO    None    None
16     CNR.TO    None    None
17      CP.TO    None    None
18     CSU.TO    None    None
19   CTC-A.TO    None    None
20     CVE.TO    None    None
21     DOL.TO    None    None
22     EMA.TO    None    None
23     ENB.TO    None    None
24      FM.TO    None    None
25     FNV.TO    None    None
26     FSV.TO    None    None
27     FTS.TO    None    None
28   GIB-A.TO    None    None
29     GIL.TO    None    None
30       H.TO    None    None
31     IFC.TO    None    None
32     IMO.TO    None    None
33       K.TO    None    None
34       L.TO    None    None
35     MFC.TO    None    None
36      MG.TO    None    None
37     MRU.TO    None    None
38      NA.TO    None    None
39     NTR.TO    None    None
40    OTEX.TO    None    None
41     POW.TO    None    None
42     PPL.TO    None    None
43     QSR.TO    None    None
44   RCI-B.TO    None    None
45      RY.TO    None    None
46     SAP.TO    None    None
47    SHOP.TO    None    None
48     SLF.TO    None    None
49      SU.TO    None    None
50       T.TO    None    None
51      TD.TO    None    None
52  TECK-B.TO    None    None
53     TOU.TO    None    None
54     TRI.TO    None    None
55     TRP.TO    None    None
56     WCN.TO    None    None
57      WN.TO    None    None
58     WPM.TO    None    None
59     WSP.TO    None    None

In [77]:
# # for index, row in df.iterrows():
# #     symbol = row['Symbol']
# #     print(symbol)
# symbol = 'WPM.TRT'
# # replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
# url_INCOME_STATEMENT = f'https://www.alphavantage.co/query?function=INCOME_STATEMENT&symbol={symbol}&apikey=9AP22VC3JPOUAYSK'
# r_INCOME_STATEMENT = requests.get(url_INCOME_STATEMENT)
# data_INCOME_STATEMENT = r_INCOME_STATEMENT.json()

# print(data_INCOME_STATEMENT)

In [78]:
# ticker = yf.Ticker("SHOP.TO")
ticker = yf.Ticker("MMM")
print(ticker)
income_stmt = ticker.get_income_stmt(freq='quarterly')
income_stmt

yfinance.Ticker object <MMM>

,2023-09-30,2023-06-30,2023-03-31,2022-12-31,2022-09-30
TaxEffectOfUnusualItems,9864000.0,0.0,0.0,-28455000.0,179784000.0
TaxRateForCalcs,0.274,0.242,0.177,0.105,0.066
NormalizedEBITDA,-2726000000.0,-8958000000.0,1241000000.0,1174000000.0,1964000000.0
TotalUnusualItems,36000000.0,NaN,NaN,-271000000.0,2724000000.0
TotalUnusualItemsExcludingGoodwill,36000000.0,NaN,NaN,-271000000.0,2724000000.0
NetIncomeFromContinuingOperationNetMinorityInterest,-2075000000.0,-6841000000.0,976000000.0,541000000.0,3859000000.0
ReconciledDepreciation,535000000.0,449000000.0,466000000.0,460000000.0,450000000.0
ReconciledCostOfRevenue,4580000000.0,4606000000.0,4613000000.0,4585000000.0,4728000000.0
EBITDA,-2690000000.0,-8958000000.0,1241000000.0,903000000.0,4688000000.0
EBIT,-2690000000.0,-8958000000.0,1241000000.0,903000000.0,4238000000.0
NetInterestIncome,-231000000.0,-96000000.0,-83000000.0,-84000000.0,-89000000.0
InterestExpense,304000000.0,144000000.0,123000000.0,115000000.0,106000000.0
InterestIncome,73000000.0,48000000.0,40000000.0,31000000.0,17000000.0
NormalizedIncome,-2101136000.0,-6841000000.0,976000000.0,783545000.0,1314784000.0
NetIncomeFromContinuingAndDiscontinuedOperation,-2075000000.0,-6841000000.0,976000000.0,541000000.0,3859000000.0
TotalExpenses,11002000000.0,17283000000.0,6790000000.0,7176000000.0,7187000000.0
TotalOperatingIncomeAsReported,-2654000000.0,-8958000000.0,1241000000.0,632000000.0,4156000000.0
DilutedAverageShares,554300000.0,553900000.0,553200000.0,552900000.0,570000000.0
BasicAverageShares,554300000.0,553900000.0,552700000.0,551900000.0,568800000.0
DilutedEPS,-3.74,-12.35,1.76,0.98,6.77
BasicEPS,-3.74,-12.35,1.77,0.98,6.79
DilutedNIAvailtoComStockholders,-2075000000.0,-6841000000.0,976000000.0,541000000.0,3859000000.0
NetIncomeCommonStockholders,-2075000000.0,-6841000000.0,976000000.0,541000000.0,3859000000.0
NetIncome,-2075000000.0,-6841000000.0,976000000.0,541000000.0,3859000000.0
MinorityInterests,-4000000.0,-5000000.0,-5000000.0,-2000000.0,-4000000.0
NetIncomeIncludingNoncontrollingInterests,-2071000000.0,-6836000000.0,981000000.0,543000000.0,3863000000.0
NetIncomeContinuousOperations,-2071000000.0,-6836000000.0,981000000.0,543000000.0,3863000000.0
EarningsFromEquityInterestNetOfTax,2000000.0,3000000.0,2000000.0,8000000.0,2000000.0
TaxProvision,-781000000.0,-2184000000.0,210000000.0,62000000.0,271000000.0
PretaxIncome,-2854000000.0,-9023000000.0,1189000000.0,597000000.0,4132000000.0
OtherIncomeExpense,-164000000.0,-65000000.0,-52000000.0,-306000000.0,2789000000.0
OtherNonOperatingIncomeExpenses,-200000000.0,-65000000.0,-52000000.0,-35000000.0,65000000.0
SpecialIncomeCharges,36000000.0,NaN,NaN,-271000000.0,2724000000.0
GainOnSaleOfBusiness,36000000.0,NaN,NaN,0.0,2724000000.0
ImpairmentOfCapitalAssets,NaN,NaN,NaN,271000000.0,NaN
NetNonOperatingInterestIncomeExpense,-231000000.0,-96000000.0,-83000000.0,-84000000.0,-89000000.0
InterestExpenseNonOperating,304000000.0,144000000.0,123000000.0,115000000.0,106000000.0
InterestIncomeNonOperating,73000000.0,48000000.0,40000000.0,31000000.0,17000000.0
OperatingIncome,-2690000000.0,-8958000000.0,1241000000.0,903000000.0,1432000000.0
OperatingExpense,6422000000.0,12677000000.0,2177000000.0,2591000000.0,2459000000.0
ResearchAndDevelopment,430000000.0,473000000.0,472000000.0,445000000.0,461000000.0
SellingGeneralAndAdministration,5992000000.0,12204000000.0,1705000000.0,2146000000.0,1998000000.0
GeneralAndAdministrativeExpense,5961000000.0,12173000000.0,1674000000.0,NaN,NaN
OtherGandA,5992000000.0,12204000000.0,1705000000.0,NaN,NaN
SalariesAndWages,-31000000.0,-31000000.0,-31000000.0,NaN,NaN
GrossProfit,3732000000.0,3719000000.0,3418000000.0,3494000000.0,3891000000.0
CostOfRevenue,4580000000.0,4606000000.0,4613000000.0,4585000000.0,4728000000.0
TotalRevenue,8312000000.0,8325000000.0,8031000000.0,8079000000.0,8619000000.0
OperatingRevenue,8312000000.0,8325000000.0,8031000000.0,8079000000.0,8619000000.0

In [79]:
balance_sheet = ticker.get_balance_sheet(freq='quarterly')
balance_sheet

,2023-09-30,2023-06-30,2023-03-31,2022-12-31,2022-09-30
TreasurySharesNumber,391716018.0,392040626.0,392360839.0,394787951.0,NaN
OrdinarySharesNumber,552317038.0,551992430.0,551672217.0,549245105.0,552742915.0
ShareIssued,944033056.0,944033056.0,944033056.0,944033056.0,552742915.0
NetDebt,10873000000.0,11729000000.0,12136000000.0,12284000000.0,12301000000.0
TotalDebt,16247000000.0,16231000000.0,16223000000.0,16200000000.0,16516000000.0
...,...,...,...,...,...
AllowanceForDoubtfulAccountsReceivable,-155000000.0,-160000000.0,-162000000.0,-174000000.0,-186000000.0
GrossAccountsReceivable,5007000000.0,5107000000.0,4800000000.0,4706000000.0,4908000000.0
CashCashEquivalentsAndShortTermInvestments,5213000000.0,4314000000.0,3969000000.0,3893000000.0,3589000000.0
OtherShortTermInvestments,73000000.0,56000000.0,145000000.0,238000000.0,185000000.0
CashAndCashEquivalents,5140000000.0,4258000000.0,3824000000.0,3655000000.0,3404000000.0

In [80]:
def get_net_income_TTM(income_stmt):
    net_income_Q1 = income_stmt.iloc[income_stmt.index.get_loc('NetIncome'), 0]
    net_income_Q2 = income_stmt.iloc[income_stmt.index.get_loc('NetIncome'), 1]
    net_income_Q3 = income_stmt.iloc[income_stmt.index.get_loc('NetIncome'), 2]
    net_income_Q4 = income_stmt.iloc[income_stmt.index.get_loc('NetIncome'), 3]
    # print(net_income_Q1, net_income_Q2, net_income_Q3, net_income_Q4)
    net_income_TTM = net_income_Q1 + net_income_Q2 + net_income_Q3 + net_income_Q4 
    return net_income_TTM

In [81]:
def get_StockholdersEquity_TTM(balance_sheet):
    StockholdersEquity_Q1 = balance_sheet.iloc[balance_sheet.index.get_loc('StockholdersEquity'), 0]
    StockholdersEquity_Q2 = balance_sheet.iloc[balance_sheet.index.get_loc('StockholdersEquity'), 1]
    StockholdersEquity_Q3 = balance_sheet.iloc[balance_sheet.index.get_loc('StockholdersEquity'), 2]
    StockholdersEquity_Q4 = balance_sheet.iloc[balance_sheet.index.get_loc('StockholdersEquity'), 3]
    # print(StockholdersEquity_Q1,StockholdersEquity_Q2,StockholdersEquity_Q3,StockholdersEquity_Q4)
    StockholdersEquity_TTM = (StockholdersEquity_Q1 + StockholdersEquity_Q2 + StockholdersEquity_Q3 + StockholdersEquity_Q4)/4
    return StockholdersEquity_TTM

In [82]:
def get_TotalAssets_TTM(balance_sheet):
    TotalAssets_Q1 = balance_sheet.iloc[balance_sheet.index.get_loc('TotalAssets'), 0]
    TotalAssets_Q2 = balance_sheet.iloc[balance_sheet.index.get_loc('TotalAssets'), 1]
    TotalAssets_Q3 = balance_sheet.iloc[balance_sheet.index.get_loc('TotalAssets'), 2]
    TotalAssets_Q4 = balance_sheet.iloc[balance_sheet.index.get_loc('TotalAssets'), 3]
    # print(TotalAssets_Q1,TotalAssets_Q2, TotalAssets_Q3,TotalAssets_Q4)
    TotalAssets_TTM = (TotalAssets_Q1 + TotalAssets_Q2 + TotalAssets_Q3 + TotalAssets_Q4)/4
    return TotalAssets_TTM

In [83]:
from requests import Session
from requests_cache import CacheMixin, SQLiteCache
from requests_ratelimiter import LimiterMixin, MemoryQueueBucket
from pyrate_limiter import Duration, RequestRate, Limiter
class CachedLimiterSession(CacheMixin, LimiterMixin, Session):
    pass

session = CachedLimiterSession(
    limiter=Limiter(RequestRate(2, Duration.SECOND*5)),  # max 2 requests per 5 seconds
    bucket_class=MemoryQueueBucket,
    backend=SQLiteCache("yfinance.cache"),
)

In [84]:
for i in range(60):
    symbol = df['Symbol'][i]
    ticker = yf.Ticker(symbol, session=session)
    income_stmt = ticker.get_income_stmt(freq='quarterly')
    balance_sheet = ticker.get_balance_sheet(freq='quarterly')
    
    net_income_TTM = get_net_income_TTM(income_stmt)
    StockholdersEquity_TTM = get_StockholdersEquity_TTM(balance_sheet)
    print(StockholdersEquity_TTM)
    TotalAssets_TTM = get_TotalAssets_TTM(balance_sheet)
    
    df['ROA_TTM'][i]= net_income_TTM/TotalAssets_TTM
    if StockholdersEquity_TTM == 0:
        df['ROE_TTM'][i] = [None]
    else:
        df['ROE_TTM'][i]= net_income_TTM/StockholdersEquity_TTM

22835750000.0
18978463750.0
5200079000.0
12678650000.0
4926250000.0
21550750000.0
0.0
74047750000.0
44222000000.0
75155250000.0
4503300000.0
9700515250.0
4343475000.0
5969400250.0
50588000000.0
38759500000.0
20653000000.0
39948750000.0
1580750000.0
5275725000.0
27905250000.0
122763750.0
11664750000.0
61784000000.0
11232250000.0
6598500000.0
963813000.0
21342000000.0
8113091500.0
1932209250.0
11474500000.0
15255500000.0
22996000000.0
5942225000.0
11379000000.0
48804500000.0
11172250000.0
6663575000.0
22349750000.0
25409250000.0
4068921750.0
22570750000.0
15632750000.0
2709000000.0
9816250000.0
109837500000.0
7120500000.0
8110722250.0
24086750000.0
40476250000.0
16475000000.0
113001250000.0
26305500000.0
13268656500.0
11705250000.0
34010750000.0
7345854500.0
7044750000.0
6804950750.0
6120150000.0

In [85]:
df.to_csv('datas/TSX60_Growth.csv', index=False)
df

       Symbol   ROA_TTM   ROE_TTM
0      ABX.TO  0.001268   0.00254
1      AEM.TO  0.090521  0.133168
2      AQN.TO  -0.01298 -0.044621
3      ATD.TO  0.104537  0.240767
4      BAM.TO  0.187294  0.326618
5      BCE.TO  0.034391  0.111597
6   BIP-UN.TO  0.005205    [None]
7      BMO.TO  0.006051  0.097748
8       BN.TO   0.00025  0.002601
9      BNS.TO  0.005906  0.107923
10     CAE.TO  0.028869  0.066662
11  CAR-UN.TO -0.015227 -0.027345
12   CCL-B.TO  0.072918  0.145367
13     CCO.TO  0.030656  0.044448
14      CM.TO  0.005019  0.092868
15     CNQ.TO  0.094112  0.183852
16     CNR.TO  0.096123   0.23798
17      CP.TO  0.054368  0.104509
18     CSU.TO  0.058545  0.332753
19   CTC-A.TO  0.025792  0.108554
20     CVE.TO  0.076132  0.148718
21     DOL.TO   0.17777  7.237617
22     EMA.TO  0.031195  0.104417
23     ENB.TO  0.019125  0.054869
24      FM.TO  0.024724  0.054308
25     FNV.TO  0.099938   0.10322
26     FSV.TO  0.044736  0.137345
27     FTS.TO  0.024085  0.073142
28   GIB-A.TO  0.102117  0.201064
29     GIL.TO  0.129711   0.24022
30       H.TO  0.034012  0.094296
31     IFC.TO  0.021224  0.078922
32     IMO.TO   0.12301  0.228344
33       K.TO  0.023304  0.041214
34       L.TO  0.054865  0.183496
35     MFC.TO  0.005676  0.098802
36      MG.TO  0.034012  0.092819
37     MRU.TO  0.070745  0.144247
38      NA.TO  0.007927  0.147697
39     NTR.TO  0.040454  0.086504
40    OTEX.TO  0.022361  0.085578
41     POW.TO  0.003212  0.103098
42     PPL.TO  0.042512  0.084502
43     QSR.TO  0.039833  0.336286
44   RCI-B.TO  0.011779  0.063976
45      RY.TO   0.00754  0.132978
46     SAP.TO  0.044339  0.089179
47    SHOP.TO -0.109692 -0.141627
48     SLF.TO  0.010984  0.147924
49      SU.TO  0.096732  0.202983
50       T.TO  0.014434  0.048619
51      TD.TO  0.007607   0.12891
52  TECK-B.TO  0.040973  0.083329
53     TOU.TO  0.055551  0.075766
54     TRI.TO  0.110817  0.196408
55     TRP.TO  0.000085  0.000294
56     WCN.TO  0.047825  0.113043
57      WN.TO  0.035787  0.247418
58     WPM.TO  0.078075  0.078668
59     WSP.TO  0.035589  0.088135

In [86]:
threshold_value = 0.1
# Filter the DataFrame where values in 'ROA_TTM' are above the threshold
filtered_df = df.loc[df['ROA_TTM'] > threshold_value]

# Sort the filtered DataFrame by 'ROA_TTM' in descending order
sorted_df = filtered_df.sort_values(by='ROA_TTM', ascending=False)
sorted_df

      Symbol   ROA_TTM   ROE_TTM
4     BAM.TO  0.187294  0.326618
21    DOL.TO   0.17777  7.237617
29    GIL.TO  0.129711   0.24022
32    IMO.TO   0.12301  0.228344
54    TRI.TO  0.110817  0.196408
3     ATD.TO  0.104537  0.240767
28  GIB-A.TO  0.102117  0.201064