In [2]:
import pandas as pd
!jupyter kernelspec list 
!which -a python
import requests
import yfinance as yf

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Available kernels:
  miniconda3    /Users/abdurrahmanabulhossain/Library/Jupyter/kernels/miniconda3
  python3       /Library/Frameworks/Python.framework/Versions/3.11/share/jupyter/kernels/python3
/Users/abdurrahmanabulhossain/miniconda3/bin/python

In [3]:
df= pd.read_csv('constituents.csv')
df = df[['Symbol']]
df

    Symbol
0      MMM
1      AOS
2      ABT
3     ABBV
4      ACN
..     ...
498    YUM
499   ZBRA
500    ZBH
501   ZION
502    ZTS

[503 rows x 1 columns]

In [4]:
# changing BRK.B in index 63 to BRK-B
df.at[63, 'Symbol'] = 'BRK-B'
df.at[80, 'Symbol'] = 'BF-B'
df['ROA_TTM'] = [None] * len(df)
df['ROE_TTM'] = [None] * len(df)
df

    Symbol ROA_TTM ROE_TTM
0      MMM    None    None
1      AOS    None    None
2      ABT    None    None
3     ABBV    None    None
4      ACN    None    None
..     ...     ...     ...
498    YUM    None    None
499   ZBRA    None    None
500    ZBH    None    None
501   ZION    None    None
502    ZTS    None    None

[503 rows x 3 columns]

In [5]:
# symbol = 'MMM'
# # replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
# url_overview = f'https://www.alphavantage.co/query?function=OVERVIEW&symbol={symbol}&apikey='
# r_overview = requests.get(url_overview)
# data_overview = r_overview.json()

# print(data_overview['ReturnOnAssetsTTM'])
# print(data_overview['ReturnOnEquityTTM'])
# print(data_overview)

In [6]:
# for i in range(25):
#     symbol = df['Symbol'][i]
#     url_overview = f'https://www.alphavantage.co/query?function=OVERVIEW&symbol={symbol}&apikey=9AP22VC3JPOUAYSK'
#     r_overview = requests.get(url_overview)
#     data_overview = r_overview.json()
#     # print(data_overview)
#     df['ROA'][i]= data_overview['ReturnOnAssetsTTM']
#     df['ROE'][i]= data_overview['ReturnOnEquityTTM']

# df

In [7]:
# for i in range(25,50):
#     symbol = df['Symbol'][i]
#     url_overview = f'https://www.alphavantage.co/query?function=OVERVIEW&symbol={symbol}&apikey=9AP22VC3JPOUAYSK'
#     r_overview = requests.get(url_overview)
#     data_overview = r_overview.json()
#     print(data_overview)
#     df['ROA'][i]= data_overview['ReturnOnAssetsTTM']
#     df['ROE'][i]= data_overview['ReturnOnEquityTTM']

# df

In [8]:
def get_net_income_TTM(income_stmt):
    net_income_Q1 = income_stmt.iloc[income_stmt.index.get_loc('NetIncome'), 0]
    net_income_Q2 = income_stmt.iloc[income_stmt.index.get_loc('NetIncome'), 1]
    net_income_Q3 = income_stmt.iloc[income_stmt.index.get_loc('NetIncome'), 2]
    
    try:
        # Code that may raise an exception
        net_income_Q4 = income_stmt.iloc[income_stmt.index.get_loc('NetIncome'), 3]
    except IndexError:
        net_income_Q4 = (net_income_Q1 + net_income_Q2 + net_income_Q3)/3
        
    if pd.isna(net_income_Q1):
        net_income_Q1 = (net_income_Q2 + net_income_Q3 + net_income_Q4)/3
    # print(net_income_Q1, net_income_Q2, net_income_Q3, net_income_Q4)
    net_income_TTM = net_income_Q1 + net_income_Q2 + net_income_Q3 + net_income_Q4
    return net_income_TTM

In [9]:
def get_StockholdersEquity_TTM(balance_sheet):
    StockholdersEquity_Q1 = balance_sheet.iloc[balance_sheet.index.get_loc('StockholdersEquity'), 0]
    StockholdersEquity_Q2 = balance_sheet.iloc[balance_sheet.index.get_loc('StockholdersEquity'), 1]
    StockholdersEquity_Q3 = balance_sheet.iloc[balance_sheet.index.get_loc('StockholdersEquity'), 2]
    
    try:
        # Code that may raise an exception
        StockholdersEquity_Q4 = balance_sheet.iloc[balance_sheet.index.get_loc('StockholdersEquity'), 3]
    except IndexError:
        StockholdersEquity_Q4 = 0
        
    # print(StockholdersEquity_Q1,StockholdersEquity_Q2,StockholdersEquity_Q3,StockholdersEquity_Q4)
    if StockholdersEquity_Q4 == 0:
        StockholdersEquity_TTM = (StockholdersEquity_Q1 + StockholdersEquity_Q2 + StockholdersEquity_Q3)/3
    else:
        StockholdersEquity_TTM = (StockholdersEquity_Q1 + StockholdersEquity_Q2 + StockholdersEquity_Q3 + StockholdersEquity_Q4)/4
        
    return StockholdersEquity_TTM

In [10]:
def get_TotalAssets_TTM(balance_sheet):
    TotalAssets_Q1 = balance_sheet.iloc[balance_sheet.index.get_loc('TotalAssets'), 0]
    TotalAssets_Q2 = balance_sheet.iloc[balance_sheet.index.get_loc('TotalAssets'), 1]
    TotalAssets_Q3 = balance_sheet.iloc[balance_sheet.index.get_loc('TotalAssets'), 2]
    
    try:
        # Code that may raise an exception
        TotalAssets_Q4 = balance_sheet.iloc[balance_sheet.index.get_loc('TotalAssets'), 3]
    except IndexError:
        TotalAssets_Q4 = 0
    
    if TotalAssets_Q4 == 0:
        TotalAssets_TTM = (TotalAssets_Q1 + TotalAssets_Q2 + TotalAssets_Q3)/3
    else:
        TotalAssets_TTM = (TotalAssets_Q1 + TotalAssets_Q2 + TotalAssets_Q3 + TotalAssets_Q4)/4
    # print(TotalAssets_Q1,TotalAssets_Q2, TotalAssets_Q3,TotalAssets_Q4)
    return TotalAssets_TTM

In [11]:
from requests import Session
from requests_cache import CacheMixin, SQLiteCache
from requests_ratelimiter import LimiterMixin, MemoryQueueBucket
from pyrate_limiter import Duration, RequestRate, Limiter
class CachedLimiterSession(CacheMixin, LimiterMixin, Session):
    pass

session = CachedLimiterSession(
    limiter=Limiter(RequestRate(2, Duration.SECOND*5)),  # max 2 requests per 5 seconds
    bucket_class=MemoryQueueBucket,
    backend=SQLiteCache("yfinance.cache"),
)

In [12]:
symbol = df['Symbol'][160]
print(symbol)
ticker = yf.Ticker(symbol, session=session)
income_stmt = ticker.get_income_stmt(freq='quarterly')
income_stmt

DUK

,2023-09-30,2023-06-30,2023-03-31,2022-12-31,2022-09-30
TaxEffectOfUnusualItems,-2240000.0,4247000.0,-142000.0,-7922839.506173,843214.756258
TaxRateForCalcs,0.028,0.137,0.142,0.15535,0.084321
NormalizedEBITDA,3722000000.0,2899000000.0,3073000000.0,2747000000.0,3620000000.0
TotalUnusualItems,-80000000.0,31000000.0,-1000000.0,-51000000.0,10000000.0
TotalUnusualItemsExcludingGoodwill,-80000000.0,31000000.0,-1000000.0,-51000000.0,10000000.0
NetIncomeFromContinuingOperationNetMinorityInterest,1404000000.0,735000000.0,1013000000.0,829000000.0,1399000000.0
ReconciledDepreciation,1353000000.0,1333000000.0,1227000000.0,1100000000.0,1491000000.0
ReconciledCostOfRevenue,4056000000.0,3493000000.0,3985000000.0,4044000000.0,4085000000.0
EBITDA,3642000000.0,2930000000.0,3072000000.0,2696000000.0,3630000000.0
EBIT,2289000000.0,1597000000.0,1845000000.0,1596000000.0,2139000000.0
NetInterestIncome,-774000000.0,-727000000.0,-720000000.0,-624000000.0,-621000000.0
InterestExpense,774000000.0,727000000.0,720000000.0,624000000.0,621000000.0
NormalizedIncome,1481760000.0,708247000.0,1013858000.0,872077160.493827,1389843214.756258
NetIncomeFromContinuingAndDiscontinuedOperation,1252000000.0,-220000000.0,804000000.0,-517000000.0,1422000000.0
TotalExpenses,5803000000.0,5179000000.0,5601000000.0,5461000000.0,5954000000.0
TotalOperatingIncomeAsReported,2111000000.0,1430000000.0,1674000000.0,1471000000.0,2024000000.0
DilutedAverageShares,771000000.0,771000000.0,770000000.0,770000000.0,770000000.0
BasicAverageShares,771000000.0,771000000.0,770000000.0,770000000.0,770000000.0
DilutedEPS,1.59,-0.32,1.01,-0.86,1.81
BasicEPS,1.59,-0.32,1.01,-0.86,1.81
DilutedNIAvailtoComStockholders,1213000000.0,-234000000.0,765000000.0,-518000000.0,1371000000.0
NetIncomeCommonStockholders,1213000000.0,-234000000.0,765000000.0,-518000000.0,1371000000.0
OtherunderPreferredStockDividend,NaN,NaN,NaN,NaN,24000000.0
PreferredStockDividends,39000000.0,14000000.0,39000000.0,26000000.0,27000000.0
NetIncome,1252000000.0,-220000000.0,804000000.0,-517000000.0,1422000000.0
MinorityInterests,-69000000.0,-16000000.0,43000000.0,8000000.0,9000000.0
NetIncomeIncludingNoncontrollingInterests,1321000000.0,-204000000.0,761000000.0,-525000000.0,1413000000.0
NetIncomeDiscontinuousOperations,-152000000.0,-955000000.0,-209000000.0,-1346000000.0,23000000.0
NetIncomeContinuousOperations,1473000000.0,751000000.0,970000000.0,821000000.0,1390000000.0
TaxProvision,42000000.0,119000000.0,155000000.0,151000000.0,128000000.0
PretaxIncome,1515000000.0,870000000.0,1125000000.0,972000000.0,1518000000.0
OtherIncomeExpense,98000000.0,198000000.0,170000000.0,74000000.0,125000000.0
OtherNonOperatingIncomeExpenses,133000000.0,147000000.0,151000000.0,99000000.0,89000000.0
SpecialIncomeCharges,-80000000.0,31000000.0,-1000000.0,-51000000.0,10000000.0
GainOnSaleOfPPE,8000000.0,31000000.0,7000000.0,6000000.0,6000000.0
WriteOff,88000000.0,0.0,8000000.0,57000000.0,-4000000.0
EarningsFromEquityInterest,45000000.0,20000000.0,20000000.0,26000000.0,26000000.0
NetNonOperatingInterestIncomeExpense,-774000000.0,-727000000.0,-720000000.0,-624000000.0,-621000000.0
InterestExpenseNonOperating,774000000.0,727000000.0,720000000.0,624000000.0,621000000.0
OperatingIncome,2191000000.0,1399000000.0,1675000000.0,1522000000.0,2014000000.0
OperatingExpense,1747000000.0,1686000000.0,1616000000.0,1417000000.0,1742000000.0
OtherTaxes,394000000.0,353000000.0,389000000.0,317000000.0,378000000.0
DepreciationAmortizationDepletionIncomeStatement,1353000000.0,1333000000.0,1227000000.0,1100000000.0,1364000000.0
DepreciationAndAmortizationInIncomeStatement,1353000000.0,1333000000.0,1227000000.0,1100000000.0,1364000000.0
GrossProfit,3938000000.0,3085000000.0,3291000000.0,2939000000.0,3756000000.0
CostOfRevenue,4056000000.0,3493000000.0,3985000000.0,4044000000.0,4212000000.0
TotalRevenue,7994000000.0,6578000000.0,7276000000.0,6983000000.0,7968000000.0
OperatingRevenue,7994000000.0,6578000000.0,7276000000.0,6983000000.0,7968000000.0

In [13]:
for i in range(503):
    symbol = df['Symbol'][i]
    ticker = yf.Ticker(symbol, session=session)
    income_stmt = ticker.get_income_stmt(freq='quarterly')
    balance_sheet = ticker.get_balance_sheet(freq='quarterly')
    
    net_income_TTM = get_net_income_TTM(income_stmt)
    print(i, net_income_TTM)
    StockholdersEquity_TTM = get_StockholdersEquity_TTM(balance_sheet)
    # print(StockholdersEquity_TTM)
    TotalAssets_TTM = get_TotalAssets_TTM(balance_sheet)
    
    df['ROA_TTM'][i]= net_income_TTM/TotalAssets_TTM
    if StockholdersEquity_TTM == 0:
        df['ROE_TTM'][i] = [None]
    else:
        df['ROE_TTM'][i]= net_income_TTM/StockholdersEquity_TTM

0 -7399000000.0
1 299200000.0
2 5162000000.0
3 6514000000.0
4 6871557000.0
5 3937000000.0
6 5121000000.0
7 3492300000.0
8 -560000000.0
9 4587000000.0
10 1133000000.0
11 5460000000.0
12 2300200000.0
13 515226000.0
14 259000000.0
15 3323601000.0
16 246387000.0
17 362814000.0
18 557100000.0
19 690000000.0
20 -1961000000.0
21 66732000000.0
22 66732000000.0
23 8760000000.0
24 20079000000.0
25 969000000.0
26 208000000.0
27 1157000000.0
28 1606000000.0
29 2256200000.0
30 8013000000.0
31 3821000000.0
32 714600000.0
33 920000000.0
34 2673000000.0
35 1277406000.0
36 7566000000.0
37 1921100000.0
38 3752375000.0
39 483597000.0
40 2723000000.0
41 1525000000.0
42 96995000000.0
43 6856000000.0
44 2282000000.0
45 2968688000.0
46 1900774000.0
47 1137200000.0
48 528100000.0
49 -11305000000.0
50 885862000.0
51 874000000.0
52 2636831000.0
53 928149000.0
54 482800000.0
55 146131000.0
56 1686000000.0
57 608000000.0
58 30503000000.0
59 733000000.0
60 2592000000.0
61 1484000000.0
62 1366243000.0
63 76813000000.0
64 1290000000.0
65 -159298000.0
66 246700000.0
67 1461800000.0
68 5188000000.0
69 1796934000.0
70 3624000000.0
71 -2862000000.0
72 5302000000.0
73 726000000.0
74 192153000.0
75 1228000000.0
76 8285000000.0
77 13917000000.0
78 671000000.0
79 747000000.0
80 765000000.0
81 1963000000.0
82 390349000.0
83 957637000.0
84 710000000.0
85 226688000.0
86 858000000.0
87 5413000000.0
88 156000000.0
89 453525000.0
90 -1624000000.0
91 1199000000.0
92 -947000000.0
93 9113000000.0
94 709100000.0
95 589960000.0
96 1095400000.0
97 2029000000.0
98 1745293000.0
99 2444000000.0
100 859000000.0
101 4000000.0
102 2111000000.0
103 474950000.0
104 5990000000.0
105 4695000000.0
106 25463000000.0
107 1170378000.0
108 7037000000.0
109 437200000.0
110 5304000000.0
111 1673000000.0
112 1381406000.0
113 13581000000.0
114 13580000000.0
115 2072000000.0
116 86000000.0
117 3049500000.0
118 749000000.0
119 10772000000.0
120 2089000000.0
121 1587000000.0
122 15152000000.0
123 1198000000.0
124 1080800000.0
125 11199000000.0
126 2375000000.0
127 1516600000.0
128 1694000000.0
129 275300000.0
130 1324420000.0
131 585000000.0
132 933000000.0
133 402597000.0
134 6394000000.0
135 2241000000.0
136 1551000000.0
137 3847000000.0
138 2797000000.0
139 8600000000.0
140 4745700000.0
141 5917000000.0
142 983400000.0
143 608973000.0
144 10043000000.0
145 3400000000.0
146 -214000000.0
147 3796000000.0
148 377000000.0
149 3190000000.0
150 924623000.0
151 3593000000.0
152 2354000000.0
153 2168517000.0
154 1218500000.0
155 1717000000.0
156 509502000.0
157 1024145000.0
158 1307000000.0
159 1243000000.0
160 1319000000.0
161 4601000000.0
162 585000000.0
163 2994000000.0
164 2715000000.0
165 1231500000.0
166 1456000000.0
167 1430900000.0
168 993000000.0
169 6080000000.0
170 4988400000.0
171 13219000000.0
172 571770000.0
173 1471679000.0
174 7883000000.0
175 474568000.0
176 2945159000.0
177 521100000.0
178 870373000.0
179 682766000.0
180 525599000.0
181 548000000.0
182 333850000.0
183 2209000000.0
184 680800000.0
185 1166402000.0
186 2144000000.0
187 842000000.0
188 813440000.0
189 791324000.0
190 41130000000.0
191 394948000.0
192 468134000.0
193 429375000.0
194 1134200000.0
195 288575000.0
196 4175000000.0
197 2556000000.0
198 473990000.0
199 524000000.0
200 -24270000000.0
201 2980000000.0
202 951352000.0
203 496900000.0
204 6162000000.0
205 1150700000.0
206 827800000.0
207 1041000000.0
208 1041000000.0
209 882800000.0
210 2157000000.0
211 1040781000.0
212 930643000.0
213 1536000000.0
214 1418000000.0
215 189020000.0
216 3302000000.0
217 10089000000.0
218 2447400000.0
219 10024000000.0
220 1251625000.0
221 5875000000.0
222 907513000.0
223 874243000.0
224 7834000000.0
225 2633000000.0
226 2322000000.0
227 -557100000.0
228 5716000000.0
229 241593000.0
230 445000000.0
231 1909041000.0
232 1593000000.0
233 1079000000.0
234 1322000000.0
235 456000000.0
236 15704000000.0
237 5414000000.0
238 877520000.0
239 755000000.0
240 640000000.0
241 2317000000.0
242 711700000.0
243 3015000000.0
244 2353000000.0
245 530000000.0
246 6924000000.0
247 617500000.0
248 822728000.0
249 3147000000.0
250 -1125000000.0
251 424981000.0
252 766300000.0
253 120000000.0
254 -1644000000.0
255 2420000000.0
256 46000000.0
257 254000000.0
258 932400000.0
259 2384000000.0
260 1516700000.0
261 833200000.0
262 490496000.0
263 1116000000.0
264 278189000.0
265 776054000.0
266 361776000.0
267 741605000.0
268 34624000000.0
269 2061000000.0
270 51253000000.0
271 366300000.0
272 826000000.0
273 1568000000.0
274 1941000000.0
275 1296000000.0
276 1130000000.0
277 1762000000.0
278 464849000.0
279 2467000000.0
280 3102661000.0
281 2988000000.0
282 1630000000.0
283 1485000000.0
284 661200000.0
285 3972450000.0
286 1011800000.0
287 670000000.0
288 147000000.0
289 3899668000.0
290 5984000000.0
291 410373000.0
292 953000000.0
293 6966000000.0
294 1352000000.0
295 6044000000.0
296 1007289000.0
297 2282000000.0
298 3024029000.0
299 1682000000.0
300 11551000000.0
301 247654000.0
302 2908000000.0
303 3466000000.0
304 1070000000.0
305 832000000.0
306 10929000000.0
307 506456000.0
308 647000000.0
309 8333200000.0
310 3488000000.0
311 3619000000.0
312 4608000000.0
313 29732000000.0
314 2314000000.0
315 869818000.0
316 1112722000.0
317 2517300000.0
318 -5833000000.0
319 77096000000.0
320 585951000.0
321 -3466000000.0
322 -545548000.0
323 931000000.0
324 255100000.0
325 4592000000.0
326 449559000.0
327 1565682000.0
328 1513000000.0
329 9806000000.0
330 1322800000.0
331 1702000000.0
332 960183000.0
333 1104000000.0
334 1209000000.0
335 4525436000.0
336 -813000000.0
337 139000000.0
338 139000000.0
339 7622000000.0
340 5052000000.0
341 721400000.0
342 500964000.0
343 2090000000.0
344 1149900000.0
345 4671000000.0
346 -209817000.0
347 -1779000000.0
348 4995135000.0
349 18888000000.0
350 1636304000.0
351 2822000000.0
352 2322649000.0
353 5225000000.0
354 1240616000.0
355 1395500000.0
356 2225300000.0
357 2455921000.0
358 9375000000.0
359 1380000000.0
360 4104800000.0
361 787700000.0
362 613900000.0
363 -1101000000.0
364 2345909000.0
365 1597300000.0
366 338982000.0
367 3765000000.0
368 509700000.0
369 8290000000.0
370 10483000000.0
371 1850000000.0
372 8014000000.0
373 7639000000.0
374 477588000.0
375 5106000000.0
376 6242000000.0
377 543655000.0
378 1418000000.0
379 817000000.0
380 318933333.3333333
381 15235000000.0
382 2741000000.0
383 3015492000.0
384 1119000000.0
385 2805000000.0
386 245540000.0
387 2121395000.0
388 2773610000.0
389 -100466000.0
390 696353000.0
391 7231000000.0
392 763000000.0
393 527800000.0
394 1739000000.0
395 3191000000.0
396 881169000.0
397 370046000.0
398 3991100000.0
399 2368000000.0
400 1638300000.0
401 906500000.0
402 752189000.0
403 471495000.0
404 1382000000.0
405 410423000.0
406 2923600000.0
407 1711880000.0
408 919721000.0
409 2481000000.0
410 1578000000.0
411 495565000.0
412 4155000000.0
413 -742000000.0
414 311900000.0
415 2776000000.0
416 1586000000.0
417 2418900000.0
418 2209431000.0
419 982800000.0
420 -17500000.0
421 994700000.0
422 217541000.0
423 3036000000.0
424 497000000.0
425 -51100000.0
426 4124500000.0
427 2467000000.0
428 2661476000.0
429 549926000.0
430 2585000000.0
431 2375000000.0
432 1034198000.0
433 1807948000.0
434 7780000000.0
435 1617100000.0
436 -1513300000.0
437 935700000.0
438 1364300000.0
439 3632000000.0
440 1910000000.0
441 789000000.0
442 403812000.0
443 503998000.0
444 10756000000.0
445 7101000000.0
446 949000000.0
447 5941000000.0
448 4109000000.0
449 1130193000.0
450 1958700000.0
451 1297000000.0
452 2184000000.0
453 333900000.0
454 5680000000.0
455 158093000.0
456 -648000000.0
457 5507000000.0
458 455897000.0
459 1262489000.0
460 6365000000.0
461 2862000000.0
462 9905333333.333334
463 2384000000.0
464 21687000000.0
465 676237000.0
466 10746000000.0
467 4827000.0
468 670666666.6666666
469 732400000.0
470 501700000.0
471 20896000000.0
472 3469700000.0
473 -215146000.0
474 1831500000.0
475 2369824000.0
476 17273000000.0
477 825200000.0
478 758000000.0
479 -3080000000.0
480 16292000000.0
481 -4827000000.0
482 2310000000.0
483 653091000.0
484 1367100000.0
485 18560000000.0
486 252455000.0
487 559400000.0
488 -2418000000.0
489 -1649000000.0
490 631000000.0
491 -1616000000.0
492 2710000000.0
493 1021000000.0
494 1818000000.0
495 33249000.0
496 1741000000.0
497 492000000.0
498 1505000000.0
499 465000000.0
500 474400000.0
501 838000000.0
502 2280000000.0

In [14]:
df.to_csv('datas/SP500_Growth.csv', index=False)
df

    Symbol   ROA_TTM   ROE_TTM
0      MMM -0.154273 -0.692969
1      AOS  0.091237   0.16375
2      ABT  0.070139  0.140899
3     ABBV  0.047815  0.469579
4      ACN  0.140081  0.281153
..     ...       ...       ...
498    YUM  0.256018 -0.175633
499   ZBRA  0.062437  0.159945
500    ZBH  0.022372  0.038667
501   ZION  0.009506  0.162128
502    ZTS  0.161319   0.49027

[503 rows x 3 columns]

In [21]:
# Set the threshold values
roa_threshold = 0.15
roe_threshold = 0.15

# Filter the DataFrame where values in 'ROA_TTM' and 'ROE_TTM' are above the threshold
filtered_df = df[(df['ROA_TTM'] > roa_threshold) & (df['ROE_TTM'] > roe_threshold)]

# filtered_df = df.loc[df['ROA_TTM'] > threshold_value]

# Sort the filtered DataFrame by 'ROA_TTM' in descending order
sorted_df = filtered_df.sort_values(by='ROA_TTM', ascending=False)
sorted_df.reset_index(drop=True, inplace=True)
sorted_df

   Symbol   ROA_TTM    ROE_TTM
0    NVDA  0.399018   0.703549
1     EMR  0.331913   0.836116
2    IDXX  0.285859   0.856762
3    AAPL  0.283917   1.607841
4      MA  0.279625   1.864778
5    ABNB  0.277569   0.872448
6     NVR  0.268512   0.417477
7    FAST  0.247926   0.341596
8    ODFL  0.247215   0.324459
9    ANET  0.240806   0.336746
10    TXN  0.238681   0.455258
11   ULTA  0.236793   0.635054
12   AMAT  0.232033   0.464884
13    GWW  0.230243   0.586972
14   KLAC  0.223125   1.108488
15   LRCX  0.209711   0.481954
16   BKNG  0.206384   8.265004
17     HD  0.206093   13.39646
18   MPWR  0.203553   0.248759
19    ITW  0.201763   1.024748
20   CPRT  0.201021     0.2283
21      V  0.196354   0.450983
22   MSFT  0.192451   0.383202
23   AVGO  0.192299   0.617813
24    EOG  0.188217   0.302491
25    ALB  0.187208   0.360199
26    JNJ   0.18688   0.470995
27   ADBE   0.18494   0.347947
28   STLD  0.183994   0.312485
29   CDNS  0.183322   0.327164
30    PHM  0.183165   0.292765
31   LULU  0.179229   0.308947
32     LW  0.178163   0.963137
33     ON  0.176973   0.328398
34  GOOGL  0.176247   0.252443
35   GOOG  0.176247   0.252443
36    VLO  0.175444   0.428281
37   MNST  0.175352   0.207822
38   VRTX  0.175236   0.230056
39    ROL  0.172806   0.328337
40   ENPH  0.169602   0.604576
41    HSY  0.167748   0.529541
42    WAT  0.167099    0.93934
43   FTNT  0.164235  36.792966
44   EXPD   0.16216   0.287869
45     EW  0.162057   0.230624
46   CTAS  0.161762   0.368242
47    ZTS  0.161319    0.49027
48    DVN  0.160275   0.338898
49    CMG  0.158993   0.445735
50    RHI  0.157621   0.295966
51     CF  0.156978   0.383278
52   MCHP  0.153535   0.378186
53    WST  0.151551   0.202022
54    NUE  0.150941   0.256649
55   MKTX  0.150254   0.217303
56    DHI  0.150251   0.222754
57   PAYX  0.150107   0.466794